name: headmate
version: <dev>
main: dev.tizu.headmate.ThisPlugin
description: Place heads the way you mate
author: tizu.dev
website: https://tizu.dev
api-version: "1.21.5"

permissions:
    headmate.wand.use:
        description: "Use the Headmate wand"
        default: true
    headmate.wand.reload.use:
        description: "Use the Headmate wand with lava, left-clicking into air to reload config"
        default: op
